using BulkAccount.Models;
using Microsoft.EntityFrameworkCore;


namespace BulkAccount.Data
{
    public class BulkAccountSolutionDbContext : DbContext 
    {
        public BulkAccountSolutionDbContext(DbContextOptions<BulkAccountSolutionDbContext> options) : base(options) { }
        public DbSet<Account> BulkAccount { get; set; }
        public DbSet<BulkAccountUpload> BulkAccountUpload { get; set; }
        public DbSet<AccountApprover> AccountApprover { get; set; }
        public DbSet<BulkAccountActionLog> BulkAccountActionLog { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BulkAccountActionLog>()
                .Property(b => b.Id)
                .ValueGeneratedOnAdd(); // This ensures EF knows the value is generated by the database
        }

        internal IEnumerable<Account> Find(Func<object, bool> value)
        {
            throw new NotImplementedException();
        }
    }
}
